In [ ]:
#NumPy stands for Numerical Python. It is a Python library used for working with arrays, especially
#multi-dimensional arrays. NumPy provides a wide range of mathematical, statistical and linear algebra
#operations that are optimised for performance.

# Why use NumPy?

# NumPy arrays are faster, more efficient, and use less memory.

# NumPy is the backbone of many Python libraries,
# such as Pandas, Scikit-learn, TensorFlow, etc.

# These libraries internally rely on NumPy
# for mathematical and numerical operations.

# NumPy is essential for data science and scientific computing in Python.
import numpy as np
numbers_list_array = np.array([10, 20, 30, 40, 50])
print(numbers_list_array)
print(type(numbers_list_array))


[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
#Array from a tuple
import numpy as np
number=np.array((1,2,3,4,5))
print(number)
print(type(number))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#A 2-D array is a table with rows and columns (a matrix). Use .shape to see its (rows, columns).

import numpy as np
numbers2=np.array([[1,2,3],[3,4,6]])
print(numbers2)
print(type(numbers2))
print(numbers2.shape)


[[1 2 3]
 [3 4 6]]
<class 'numpy.ndarray'>
(2, 3)


In [ ]:
import numpy as np
numbers3=np.array([[[1,2,3],[4,5,6]],
                  [[1,2,3],[4,5,6]]])
print(numbers3)
print(type(numbers3))
print(numbers3.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(2, 2, 3)


In [ ]:
import numpy as np
marks_matrix = np.array([[90, 85, 80],
 [79, 75, 65]])
print(marks_matrix)
# row index and column index
print(marks_matrix[0, 0])
print(marks_matrix[0, 1])
print(marks_matrix[0, 2])
print(marks_matrix[1, 0])
print(marks_matrix[1, 1])
print(marks_matrix[1, 2])
print(marks_matrix[0])

[[90 85 80]
 [79 75 65]]
90
85
80
79
75
65
[90 85 80]


In [ ]:
import numpy as np
cube_data_array = np.array([[[1, 2, 3], [4, 5, 6]],
 [[7, 8, 9], [10, 11, 12]]])
print(cube_data_array)
print(cube_data_array[0, 0, 0])
print(cube_data_array[0, 1, 2])
print(cube_data_array[1, 0, 1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
6
8


In [ ]:
import numpy as np
scores_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(scores_array)
sliced_array = scores_array[2:5]
print(sliced_array)
print(scores_array[:4]) # from start to index 3
print(scores_array[5:]) # from index 5 to end
print(scores_array[:]) # whole array
print(scores_array[::2]) # every 2nd element
print(scores_array[::3]) # every 3rd element
print(scores_array[-3:]) # last three elements
print(scores_array[-5:-2]) # negative start and end

[ 10  20  30  40  50  60  70  80  90 100]
[30 40 50]
[10 20 30 40]
[ 60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]
[10 30 50 70 90]
[ 10  40  70 100]
[ 80  90 100]
[60 70 80]


In [ ]:
import numpy as np
scores_array = np.array([10, 20, 30, 40, 50])
print(scores_array)
print(scores_array[0]) # first element
print(scores_array[2]) # third element
print(scores_array[-1]) # last element
print(scores_array[-2]) # second last element

[10 20 30 40 50]
10
30
50
40


In [ ]:
#Slicing a 2-D array means getting a part of the array by specifying a start and end. The syntax is: array name,
#square brackets, then two slices - one for rows and one for columns: array[row slice, column
#slice].
#Example: [0:2, 1:3] means pick rows from index 0 to 1 (because the end is not included) and columns
#from index 1 to 2.
import numpy as np
table_data_array = np.array([[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90],
 [100, 110, 120]])
#print(table_data_array)
#print(table_data_array[0:2, :]) # first two rows, all columns
print(table_data_array[1:3, 1:3]) # rows 1-2 and columns 1-2
#print(table_data_array[:, 1]) # all rows, second column
#print(table_data_array[0::2, :]) # every 2nd row starting from 0
#print(table_data_array[-2:, :]) # last two rows
#print(table_data_array[:, 0:2]) # first two columns

[[50 60]
 [80 90]]


In [ ]:
import numpy as np
#one_d_array = np.array([5, 10, 15, 20])
#print(one_d_array)
#print(one_d_array.shape)
two_d_array = np.array([[1, 2],
 [3, 4],
 [5, 6]])
print(two_d_array)
print(two_d_array.shape)
#three_d_array = np.array([[[1, 2], [3, 4]],
 #[[5, 6], [7, 8]]])
#print(three_d_array)
#print(three_d_array.shape)


[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
#Reshaping means changing the shape of an array. When we reshape, we are not changing the data - we
#are just changing how it is laid out in rows and columns. For example, a simple 1-D array can be turned into a
#matrix, or even into a 3-D block of data. This is super useful when working with images, matrices or machine
#learning models, where the shape of your data matters.
import numpy as np
original_array = np.array([1, 2, 3, 4, 5, 6])
print(original_array.shape)
reshaped_array = original_array.reshape(3, 2)
print(reshaped_array)

(6,)
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
numbers_array = np.array([10, 20, 30])
for number in numbers_array:
 print(number)

10
20
30


In [ ]:
#iterating into 2D arrays
import numpy as np
table_array = np.array([[1, 2],
 [3, 4]])
for row in table_array:
 print(row)
# Nested loop to access each element
for row in table_array:
 for item in row:
  print(item)


[1 2]
[3 4]
1
2
3
4


In [ ]:
#Joining arrays simply means combining two or more arrays into one. NumPy makes this easy using functions like concatenate
import numpy as np
array1=np.array([10,20,30])
array2=np.array([40,50,60])
array3=np.concatenate([array1,array2])
print(array3)

[10 20 30 40 50 60]


In [ ]:
#Splitting means dividing one array into multiple smaller parts. It is really useful when you want to break data into sections.
import numpy as np
numbers_array = np.array([10, 20, 30, 40, 50, 60])
print(numbers_array)
# Split into 3 equal parts
split_result = np.array_split(numbers_array, 3)
for part in split_result:
 print(part)


[10 20 30 40 50 60]
[10 20]
[30 40]
[50 60]


In [ ]:
#Searching means finding the positions of certain values, or locating which elements satisfy a particular
#condition. NumPy provides the where() method to search an array for a certain value and return the indices
#that match. There is also searchsorted(), which performs a binary search in the array and returns the
#index where the specified value would be inserted to maintain the sort order.

import numpy as np
numbers_array = np.array([10, 20, 30, 40, 50, 60, 70])
print(numbers_array)
result_forty = np.where(numbers_array == 40)
print(result_forty)
greater_than_thirtyfive = np.where(numbers_array > 35)
print(greater_than_thirtyfive)




[10 20 30 40 50 60 70]
(array([3]),)
(array([3, 4, 5, 6]),)


In [ ]:
import numpy as np
unsorted_numbers = np.array([5, 2, 9, 1, 7])
print("Original array", unsorted_numbers)
sorted_numbers = np.sort(unsorted_numbers)
print("Sorted array", sorted_numbers)


Original array [5 2 9 1 7]
Sorted array [1 2 5 7 9]


In [ ]:
#Filtering means getting only those elements that meet a certain condition. It is a powerful technique used
#in data science to clean, sort or extract meaningful information. We create a boolean array (True / False)
#from a condition and use it as an index.
import numpy as np
ages_array = np.array([12, 17, 19, 21, 15, 18, 22])
print(ages_array)
above_18 = ages_array > 18 # boolean array
print(above_18)
filtered_result = ages_array[above_18]
print(filtered_result)

[12 17 19 21 15 18 22]
[False False  True  True False False  True]
[19 21 22]
